version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:80"
      - "4005:4005"
    volumes:
      - .:/app
      - ~/common-lisp:/common-lisp
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ultralisp
      POSTGRES_PASSWORD: ultralisp
      POSTGRES_RO_USER: ultralisp_ro
      POSTGRES_RO_PASSWORD: ultralisp_ro
  postgres:
    image: "postgres:10"
    restart: always
    environment:
      POSTGRES_USER: ultralisp
      POSTGRES_PASSWORD: ultralisp
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    