version: 2
jobs:
  sbcl:
    docker:
      - image: 40ants/base-lisp-image:0.12.0-sbcl-bin
      - image: postgres:10
        environment:
          POSTGRES_USER: ultralisp
          POSTGRES_PASSWORD: ultralisp

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            install-dependencies
            ros install rove
            ros install cxxxr/sblint
            # Without this package cl-coveralls fails when uploading
            # report to the server
            apt-get update 
            apt-get install -y file
      - run:
          name: Check environment
          command: |
            set -x
            echo '================================================'
            env | grep -v -i token | sort
            echo '================================================'
            pwd
            echo '================================================'
            ls -lh
            echo '================================================'
            ros config
            echo '================================================'
      - run:
          name: Run linter
          command: qlot exec sblint ultralisp.asd ultralisp-test.asd
      - run:
          name: Run tests
          # rove as a separate command goes into a infinite loop for some reason
          # that is why here it is commented and start via ros run instead
          # command: qlot exec rove ultralisp-test.asd
          command: |
            COVERALLS=true \
            COVERALLS_REPO_TOKEN=oSCs0D19ccZ2cRcsUmZkfYL8ph5vV1Ni4 \
            CC=gcc \
            qlot exec ros run \
               --eval '(ql:quickload :ultralisp-test :silent t)' \
               --eval '(ql:quickload :cl-coveralls :silent t)' \
               --eval '(log:config :sane2 :warn)' \
               --eval '(let ((result (coveralls:with-coveralls (:exclude (list ".qlot/"))
                                       (rove:run :ultralisp-test))))
                         (uiop:quit (if result 0 1)))'

workflows:
  version: 2
  build:
    jobs:
      - sbcl
