name: Add Version Tag

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: butlerlogic/action-autotag@stable
      with:
        regex_pattern: "^(?<version>\\d+\\.\\d+\\.\\d+(.+)?)\\n?"
        root: ./ChangeLog.rst
        tag_prefix: "v"
        dry_run: true
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
