# This is a basic workflow that is manually triggered

name: Deploy Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Version number to deploy'
        default: 'v0.1.0'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to production
      uses: svetlyak40wt/ansible-playbook-docker-action@master
      env:
        ANSIBLE_STDOUT_CALLBACK: debug
        ANSIBLE_FORCE_COLOR: true
      with:
        playbookName: ".ansible/playbooks/ultralisp.yml"
        inventoryFile: ".ansible/inventory/hosts.yml"
        keyFile: ".ansible/deploy"
        keyFileVaultPass: ${{ secrets.ANSIBLE_SSH_KEY_PASS }}
        extraVars: "-e ultralisp_version=${{ inputs.version }}"
        verbosity: "vvv"
